#type_of_cam:
#0---stereo kitti
#1---stereo euroc
#2---T265
type_of_cam: 0
#depth image is aligned to left cam0
image_width: 640
image_height: 360

T_world_body:
[ 1.0,  0.0,  0.0,  0.0,
  0.0,  1.0,  0.0,  0.0,
  0.0,  0.0,  1.0,  0.0,
  0.0,  0.0,  0.0,  1.0]

cam0_intrinsics: [343.4963684082031, 343.4963684082031, 320, 180] #fx fy cx cy
cam0_distortion_coeffs: [0.0, 0.0, 0.0, 0.0] #k1 k2 r1 r2
T_body_cam0:
[ 0.0,  0.0,    1,  0.12,
   -1,  0.0,  0.0,   0.0,
  0.0,   -1,  0.0,   0.0,
  0.0,  0.0,  0.0,   1.0]

T_cam0_cam1:
[ 1.0,  0.0,  0.0,   -0.05,
  0.0,  1.0,  0.0,   0.0,
  0.0,  0.0,  1.0,   0.0,
  0.0,  0.0,  0.0,   1.0]

#reserved para for future functions
para_1: 0
para_2: 0
para_3: 0
para_4: 0



